[nodes]

[nodes.host1]
posX = 200
posY = 200
model = "PC"

[nodes.n1]
posX = 300
posY = 200
model = "router"

[nodes.n2]
posX = 400
posY = 100
model = "router"

[nodes.suricata]
posX = 500
posY = 200 
model = "router"

[nodes.host2]
posX = 500
posY = 200 
model = "PC"

[links]

[links.1]
node1 = "host1"
node2 = "n1"

[links.2]
node1 = "host1"
node2 = "n2"

[links.3]
node1 = "n1"
node2 = "suricata"

[links.4]
node1 = "n2" 
node2 = "suricata"

[links.5]
node1 = "suricata"
node2 = "host2"

[scripts]
